/*
 * This source file was generated by the Gradle 'init' task
 */
package jsonparser;

public class App {
    public static void main(String[] args) throws Throwable {
        jsonParser parser = new jsonParser("localhost", 8008);
        System.out.println(parser.getClosestObjectClass());
    }
}
